// <auto-generated />
using System;
using FieldPulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldPulse.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523065301_AddSoftDeletesAndSeedData")]
    partial class AddSoftDeletesAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldPulse.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "123 Industrial Blvd",
                            City = "Detroit",
                            CreatedAt = new DateTime(2026, 2, 22, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            Email = "contact@acme.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Acme Corporation",
                            Notes = "Key account - quarterly reviews",
                            Phone = "+1-555-0101",
                            PostalCode = "48201",
                            UpdatedAt = new DateTime(2026, 5, 13, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "456 Rural Route 7",
                            City = "Springfield",
                            CreatedAt = new DateTime(2026, 3, 24, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            Email = "smith@farms.local",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Smith Family Farms",
                            Notes = "Agricultural equipment maintenance",
                            Phone = "+1-555-0202",
                            PostalCode = "62701",
                            UpdatedAt = new DateTime(2026, 5, 18, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "789 Downtown Plaza",
                            City = "Chicago",
                            CreatedAt = new DateTime(2026, 4, 23, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            Email = "ops@metropm.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metro Property Management",
                            Phone = "+1-555-0303",
                            PostalCode = "60601",
                            UpdatedAt = new DateTime(2026, 5, 21, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        });
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DueDate");

                    b.HasIndex("Status");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 2450.00m,
                            CreatedAt = new DateTime(2026, 5, 18, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            CustomerEmail = "contact@acme.com",
                            CustomerName = "Acme Corporation",
                            Description = "AC Unit Replacement - Invoice",
                            DueDate = new DateTime(2026, 5, 21, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            IsDeleted = false,
                            PaidAt = new DateTime(2026, 5, 22, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 5, 22, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 900.00m,
                            CreatedAt = new DateTime(2026, 5, 22, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            CustomerEmail = "smith@farms.local",
                            CustomerName = "Smith Family Farms",
                            Description = "Electrical Panel Upgrade - Deposit",
                            DueDate = new DateTime(2026, 6, 6, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            IsDeleted = false,
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 5, 22, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 450.00m,
                            CreatedAt = new DateTime(2026, 5, 23, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            CustomerEmail = "ops@metropm.com",
                            CustomerName = "Metro Property Management",
                            Description = "Annual Maintenance Contract - Q2",
                            DueDate = new DateTime(2026, 6, 22, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            IsDeleted = false,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 5, 23, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        });
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("Status");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            ActualCost = 2450.00m,
                            CompletedAt = new DateTime(2026, 5, 18, 20, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            CreatedAt = new DateTime(2026, 5, 13, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Replace old AC unit with new energy-efficient model",
                            EstimatedCost = 2500.00m,
                            IsDeleted = false,
                            Notes = "Customer very satisfied",
                            ScheduledDate = new DateTime(2026, 5, 18, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            StartedAt = new DateTime(2026, 5, 18, 15, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            Status = 3,
                            TechnicianId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Title = "AC Unit Replacement",
                            UpdatedAt = new DateTime(2026, 5, 18, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 5, 20, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            CustomerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Upgrade main panel from 100A to 200A",
                            EstimatedCost = 1800.00m,
                            IsDeleted = false,
                            Notes = "Waiting for city inspection",
                            ScheduledDate = new DateTime(2026, 5, 23, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            StartedAt = new DateTime(2026, 5, 23, 14, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            Status = 2,
                            TechnicianId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Title = "Electrical Panel Upgrade",
                            UpdatedAt = new DateTime(2026, 5, 23, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 5, 22, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            CustomerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Q2 preventive maintenance visit",
                            EstimatedCost = 450.00m,
                            IsDeleted = false,
                            ScheduledDate = new DateTime(2026, 5, 26, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            Status = 1,
                            TechnicianId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Title = "Annual Maintenance Contract",
                            UpdatedAt = new DateTime(2026, 5, 22, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 5, 23, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            CustomerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Burst pipe in basement - emergency call",
                            EstimatedCost = 800.00m,
                            IsDeleted = false,
                            Notes = "After hours - urgent",
                            ScheduledDate = new DateTime(2026, 5, 24, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            Status = 0,
                            Title = "Emergency Pipe Repair",
                            UpdatedAt = new DateTime(2026, 5, 23, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        });
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 23, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            Email = "john.miller@FieldPulse.local",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Miller",
                            Phone = "+1-555-0404",
                            Specialization = "HVAC",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 5, 13, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 22, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            Email = "sarah.chen@FieldPulse.local",
                            FirstName = "Sarah",
                            IsDeleted = false,
                            LastName = "Chen",
                            Phone = "+1-555-0505",
                            Specialization = "Electrical",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 5, 18, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2025, 11, 24, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385),
                            Email = "marcus.j@FieldPulse.local",
                            FirstName = "Marcus",
                            IsDeleted = false,
                            LastName = "Johnson",
                            Phone = "+1-555-0606",
                            Specialization = "Plumbing",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 5, 22, 6, 53, 1, 174, DateTimeKind.Utc).AddTicks(6385)
                        });
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.Invoice", b =>
                {
                    b.HasOne("FieldPulse.Core.Entities.Customer", null)
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.Job", b =>
                {
                    b.HasOne("FieldPulse.Core.Entities.Customer", "Customer")
                        .WithMany("Jobs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FieldPulse.Core.Entities.Technician", "Technician")
                        .WithMany("AssignedJobs")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.User", b =>
                {
                    b.OwnsOne("FieldPulse.Core.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("FieldPulse.Core.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FieldPulse.Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("FieldPulse.Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FieldPulse.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("FieldPulse.Core.Entities.Technician", b =>
                {
                    b.Navigation("AssignedJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
