import React, { useState, useCallback, useEffect, useMemo } from 'react';
import {
  Users,
  UserPlus,
  Sparkles,
  Brain,
  Target,
  MessageSquare,
  TrendingUp,
  Trash2,
  Edit3,
  CheckCircle,
  AlertCircle,
  Loader2,
  ChevronDown,
  ChevronRight,
  Lightbulb,
  Wand2,
  Shield,
  Zap,
  BarChart3,
  PieChart,
  Activity,
} from 'lucide-react';
import { cn } from '../../lib/utils';
import { Button } from '../common/Button';
import { Input } from '../common/Input';
import api from '../../services/api';
import { formatDateTime } from '@/utils/dateFormat';

// ============================================================================
// Types
// ============================================================================

export type PersonaDomain =
  | 'human_resources'
  | 'software_development'
  | 'data_analysis'
  | 'legal'
  | 'marketing'
  | 'finance'
  | 'project_management'
  | 'customer_support'
  | 'sales'
  | 'operations'
  | 'research'
  | 'content_creation'
  | 'design'
  | 'security'
  | 'devops'
  | 'custom';

export interface PersonaSkill {
  name: string;
  description: string;
  proficiency: number;
  relatedTools?: string[];
}

export interface PersonaProfile {
  id: string;
  name: string;
  tagline: string;
  domain: PersonaDomain;
  version: number;
  expertise: string[];
  skills: PersonaSkill[];
  systemPrompt: string;
  isAutoGenerated: boolean;
  usageCount: number;
  successRate: number;
  lastUsedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PersonaAnalytics {
  personaId: string;
  totalTasks: number;
  successfulTasks: number;
  failedTasks: number;
  averageQualityRating: number;
  mostCommonTaskTypes: { type: string; count: number }[];
  learningCount: number;
  lastActiveAt?: string;
}

export interface PersonaLearning {
  id: string;
  personaId: string;
  taskType: string;
  pattern: string;
  confidence: number;
  applicationCount: number;
  createdAt: string;
}

export interface PersonaManagerPanelProps {
  /** Agent ID for persona management */
  agentId: string;
  /** Agent name for display */
  agentName?: string;
  /** Callback when a persona is activated */
  onPersonaActivated?: (persona: PersonaProfile) => void;
  /** Callback when a persona is deactivated */
  onPersonaDeactivated?: () => void;
  /** Additional className */
  className?: string;
}

// ============================================================================
// Domain Configuration
// ============================================================================

const DOMAIN_LABELS: Record<PersonaDomain, { label: string; icon: React.ReactNode; color: string }> = {
  human_resources: { label: 'Human Resources', icon: <Users className="w-4 h-4" />, color: 'text-pink-400' },
  software_development: { label: 'Software Development', icon: <Zap className="w-4 h-4" />, color: 'text-blue-400' },
  data_analysis: { label: 'Data Analysis', icon: <TrendingUp className="w-4 h-4" />, color: 'text-cyan-400' },
  legal: { label: 'Legal', icon: <Shield className="w-4 h-4" />, color: 'text-slate-400' },
  marketing: { label: 'Marketing', icon: <Target className="w-4 h-4" />, color: 'text-orange-400' },
  finance: { label: 'Finance', icon: <TrendingUp className="w-4 h-4" />, color: 'text-green-400' },
  project_management: { label: 'Project Management', icon: <Target className="w-4 h-4" />, color: 'text-purple-400' },
  customer_support: { label: 'Customer Support', icon: <MessageSquare className="w-4 h-4" />, color: 'text-yellow-400' },
  sales: { label: 'Sales', icon: <Target className="w-4 h-4" />, color: 'text-red-400' },
  operations: { label: 'Operations', icon: <Zap className="w-4 h-4" />, color: 'text-indigo-400' },
  research: { label: 'Research', icon: <Brain className="w-4 h-4" />, color: 'text-violet-400' },
  content_creation: { label: 'Content Creation', icon: <Edit3 className="w-4 h-4" />, color: 'text-fuchsia-400' },
  design: { label: 'Design', icon: <Sparkles className="w-4 h-4" />, color: 'text-rose-400' },
  security: { label: 'Security', icon: <Shield className="w-4 h-4" />, color: 'text-amber-400' },
  devops: { label: 'DevOps', icon: <Zap className="w-4 h-4" />, color: 'text-teal-400' },
  custom: { label: 'Custom', icon: <Wand2 className="w-4 h-4" />, color: 'text-gray-400' },
};

const ALL_DOMAINS: PersonaDomain[] = [
  'human_resources',
  'software_development',
  'data_analysis',
  'legal',
  'marketing',
  'finance',
  'project_management',
  'customer_support',
  'sales',
  'operations',
  'research',
  'content_creation',
  'design',
  'security',
  'devops',
  'custom',
];

// ============================================================================
// Chart Components
// ============================================================================

/**
 * DonutChart - Circular progress visualization for success rate
 */
const DonutChart: React.FC<{
  value: number;
  total: number;
  label: string;
  color?: string;
  size?: number;
}> = ({ value, total, label, color = '#10B981', size = 120 }) => {
  const percentage = total > 0 ? (value / total) * 100 : 0;
  const strokeWidth = 12;
  const radius = (size - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (percentage / 100) * circumference;

  return (
    <div className="flex flex-col items-center">
      <svg width={size} height={size} className="transform -rotate-90">
        {/* Background circle */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke="#374151"
          strokeWidth={strokeWidth}
        />
        {/* Progress circle */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeDasharray={circumference}
          strokeDashoffset={strokeDashoffset}
          strokeLinecap="round"
          className="transition-all duration-500 ease-out"
        />
      </svg>
      <div className="absolute flex flex-col items-center justify-center" style={{ width: size, height: size }}>
        <span className="text-2xl font-bold text-white">{Math.round(percentage)}%</span>
        <span className="text-xs text-gray-400">{label}</span>
      </div>
    </div>
  );
};

/**
 * HorizontalBarChart - Task type distribution visualization
 */
const HorizontalBarChart: React.FC<{
  data: { type: string; count: number }[];
  maxItems?: number;
}> = ({ data, maxItems = 5 }) => {
  const sortedData = [...data].sort((a, b) => b.count - a.count).slice(0, maxItems);
  const maxCount = Math.max(...sortedData.map(d => d.count), 1);

  const colors = [
    'bg-indigo-500',
    'bg-emerald-500',
    'bg-amber-500',
    'bg-rose-500',
    'bg-cyan-500',
  ];

  if (sortedData.length === 0) {
    return (
      <div className="text-center py-4 text-gray-500 text-sm">
        No task data available
      </div>
    );
  }

  return (
    <div className="space-y-3">
      {sortedData.map((item, index) => (
        <div key={item.type} className="space-y-1">
          <div className="flex justify-between text-xs">
            <span className="text-gray-300 truncate max-w-[150px]" title={item.type}>
              {item.type}
            </span>
            <span className="text-gray-400">{item.count}</span>
          </div>
          <div className="h-2 bg-slate-700 rounded-full overflow-hidden">
            <div
              className={cn('h-full rounded-full transition-all duration-500', colors[index % colors.length])}
              style={{ width: `${(item.count / maxCount) * 100}%` }}
            />
          </div>
        </div>
      ))}
    </div>
  );
};

/**
 * QualityGauge - Semi-circular gauge for quality rating
 */
const QualityGauge: React.FC<{
  value: number;
  maxValue?: number;
  size?: number;
}> = ({ value, maxValue = 5, size = 140 }) => {
  const percentage = Math.min((value / maxValue) * 100, 100);
  const angle = (percentage / 100) * 180;

  // Determine color based on value
  const getColor = () => {
    const ratio = value / maxValue;
    if (ratio >= 0.8) return '#10B981'; // emerald
    if (ratio >= 0.6) return '#F59E0B'; // amber
    if (ratio >= 0.4) return '#F97316'; // orange
    return '#EF4444'; // red
  };

  return (
    <div className="relative flex flex-col items-center">
      <svg width={size} height={size / 2 + 10} viewBox={`0 0 ${size} ${size / 2 + 10}`}>
        {/* Background arc */}
        <path
          d={`M ${size * 0.1} ${size / 2} A ${size * 0.4} ${size * 0.4} 0 0 1 ${size * 0.9} ${size / 2}`}
          fill="none"
          stroke="#374151"
          strokeWidth={10}
          strokeLinecap="round"
        />
        {/* Value arc */}
        <path
          d={`M ${size * 0.1} ${size / 2} A ${size * 0.4} ${size * 0.4} 0 0 1 ${size * 0.9} ${size / 2}`}
          fill="none"
          stroke={getColor()}
          strokeWidth={10}
          strokeLinecap="round"
          strokeDasharray={`${(angle / 180) * (Math.PI * size * 0.4)} ${Math.PI * size * 0.4}`}
          className="transition-all duration-500"
        />
        {/* Needle */}
        <line
          x1={size / 2}
          y1={size / 2}
          x2={size / 2 + Math.cos((180 - angle) * Math.PI / 180) * (size * 0.3)}
          y2={size / 2 - Math.sin((180 - angle) * Math.PI / 180) * (size * 0.3)}
          stroke={getColor()}
          strokeWidth={3}
          strokeLinecap="round"
          className="transition-all duration-500"
        />
        {/* Center dot */}
        <circle cx={size / 2} cy={size / 2} r={6} fill={getColor()} />
      </svg>
      <div className="text-center -mt-2">
        <span className="text-xl font-bold text-white">{value.toFixed(1)}</span>
        <span className="text-gray-400 text-sm">/{maxValue}</span>
      </div>
    </div>
  );
};

/**
 * SkillRadar - Simplified skill visualization with concentric circles
 */
const SkillRadar: React.FC<{
  skills: PersonaSkill[];
  size?: number;
}> = ({ skills, size = 200 }) => {
  const displaySkills = skills.slice(0, 6);
  const centerX = size / 2;
  const centerY = size / 2;
  const maxRadius = size * 0.4;
  const angleStep = (2 * Math.PI) / displaySkills.length;

  // Generate polygon points for skills
  const points = displaySkills.map((skill, i) => {
    const angle = i * angleStep - Math.PI / 2;
    const radius = (skill.proficiency / 100) * maxRadius;
    return {
      x: centerX + Math.cos(angle) * radius,
      y: centerY + Math.sin(angle) * radius,
      labelX: centerX + Math.cos(angle) * (maxRadius + 20),
      labelY: centerY + Math.sin(angle) * (maxRadius + 20),
      skill,
    };
  });

  const polygonPoints = points.map(p => `${p.x},${p.y}`).join(' ');

  if (displaySkills.length < 3) {
    return (
      <div className="text-center py-4 text-gray-500 text-sm">
        Need at least 3 skills for radar chart
      </div>
    );
  }

  return (
    <svg width={size} height={size} className="overflow-visible">
      {/* Background circles */}
      {[0.25, 0.5, 0.75, 1].map((ratio, i) => (
        <circle
          key={i}
          cx={centerX}
          cy={centerY}
          r={maxRadius * ratio}
          fill="none"
          stroke="#374151"
          strokeWidth={1}
          strokeDasharray={i < 3 ? '4 4' : ''}
        />
      ))}

      {/* Axis lines */}
      {displaySkills.map((_, i) => {
        const angle = i * angleStep - Math.PI / 2;
        return (
          <line
            key={i}
            x1={centerX}
            y1={centerY}
            x2={centerX + Math.cos(angle) * maxRadius}
            y2={centerY + Math.sin(angle) * maxRadius}
            stroke="#4B5563"
            strokeWidth={1}
          />
        );
      })}

      {/* Skill polygon */}
      <polygon
        points={polygonPoints}
        fill="rgba(99, 102, 241, 0.2)"
        stroke="#6366F1"
        strokeWidth={2}
        className="transition-all duration-500"
      />

      {/* Skill points */}
      {points.map((point, i) => (
        <g key={i}>
          <circle
            cx={point.x}
            cy={point.y}
            r={4}
            fill="#6366F1"
            stroke="#1F2937"
            strokeWidth={2}
          />
          <text
            x={point.labelX}
            y={point.labelY}
            textAnchor="middle"
            dominantBaseline="middle"
            className="text-[10px] fill-gray-400"
          >
            {point.skill.name.length > 12 ? point.skill.name.slice(0, 10) + '...' : point.skill.name}
          </text>
        </g>
      ))}
    </svg>
  );
};

/**
 * MiniSparkline - Simple trend visualization
 */
const MiniSparkline: React.FC<{
  data: number[];
  width?: number;
  height?: number;
  color?: string;
}> = ({ data, width = 80, height = 24, color = '#6366F1' }) => {
  if (data.length < 2) return null;

  const max = Math.max(...data);
  const min = Math.min(...data);
  const range = max - min || 1;

  const points = data.map((value, i) => {
    const x = (i / (data.length - 1)) * width;
    const y = height - ((value - min) / range) * height;
    return `${x},${y}`;
  }).join(' ');

  return (
    <svg width={width} height={height} className="overflow-visible">
      <polyline
        points={points}
        fill="none"
        stroke={color}
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
};

// ============================================================================
// Main Component
// ============================================================================

/**
 * PersonaManagerPanel - Manage AI personas for an agent
 * Allows creating, editing, activating, and viewing analytics for personas
 */
export const PersonaManagerPanel: React.FC<PersonaManagerPanelProps> = ({
  agentId,
  agentName,
  onPersonaActivated,
  onPersonaDeactivated,
  className,
}) => {
  // Personas state
  const [personas, setPersonas] = useState<PersonaProfile[]>([]);
  const [activePersonaId, setActivePersonaId] = useState<string | null>(null);
  const [selectedPersona, setSelectedPersona] = useState<PersonaProfile | null>(null);

  // Analytics state
  const [analytics, setAnalytics] = useState<PersonaAnalytics | null>(null);
  const [learnings, setLearnings] = useState<PersonaLearning[]>([]);

  // Create persona state
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [createMode, setCreateMode] = useState<'manual' | 'generate'>('generate');
  const [newPersonaName, setNewPersonaName] = useState('');
  const [newPersonaDomain, setNewPersonaDomain] = useState<PersonaDomain>('custom');
  const [newPersonaTagline, setNewPersonaTagline] = useState('');
  const [generateTask, setGenerateTask] = useState('');

  // UI state
  const [isLoading, setIsLoading] = useState(false);
  const [isLoadingPersonas, setIsLoadingPersonas] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [expandedSection, setExpandedSection] = useState<string | null>('list');

  // Load personas on mount
  useEffect(() => {
    loadPersonas();
  }, [agentId]);

  // Load analytics when persona selected
  useEffect(() => {
    if (selectedPersona) {
      loadPersonaAnalytics(selectedPersona.id);
      loadPersonaLearnings(selectedPersona.id);
    }
  }, [selectedPersona]);

  const loadPersonas = async () => {
    setIsLoadingPersonas(true);
    setError(null);
    try {
      const response = await api.get(`/agentic/agents/${agentId}/personas`);
      const personaList = response.data?.personas || [];
      setPersonas(personaList);

      // Check if there's an active persona
      const activePersona = personaList.find((p: PersonaProfile) => p.id === response.data?.activePersonaId);
      if (activePersona) {
        setActivePersonaId(activePersona.id);
        setSelectedPersona(activePersona);
      }
    } catch (err) {
      console.error('Failed to load personas:', err);
      setError('Failed to load personas');
    } finally {
      setIsLoadingPersonas(false);
    }
  };

  const loadPersonaAnalytics = async (personaId: string) => {
    try {
      const response = await api.get(`/agentic/personas/${personaId}/analytics`);
      setAnalytics(response.data?.analytics || null);
    } catch {
      setAnalytics(null);
    }
  };

  const loadPersonaLearnings = async (personaId: string) => {
    try {
      const response = await api.get(`/agentic/personas/${personaId}/learnings`);
      setLearnings(response.data?.learnings || []);
    } catch {
      setLearnings([]);
    }
  };

  const handleCreatePersona = async () => {
    if (createMode === 'manual' && !newPersonaName.trim()) {
      setError('Please enter a persona name');
      return;
    }
    if (createMode === 'generate' && !generateTask.trim()) {
      setError('Please describe the task for auto-generation');
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      if (createMode === 'generate') {
        setIsGenerating(true);
        // Use the AI-powered persona generation
        const response = await api.post('/agentic/personas/generate', {
          domain: newPersonaDomain,
          triggeringTask: generateTask,
          cliType: 'claude', // Default CLI type
        });

        if (response.data?.persona) {
          // Save the generated persona to the agent
          const saveResponse = await api.post(`/agentic/agents/${agentId}/personas`, {
            ...response.data.persona,
            domain: response.data.persona.domain,
          });

          if (saveResponse.data?.persona) {
            setPersonas(prev => [...prev, saveResponse.data.persona]);
            setSelectedPersona(saveResponse.data.persona);
          }
        }
      } else {
        // Manual creation
        const response = await api.post(`/agentic/agents/${agentId}/personas`, {
          name: newPersonaName,
          domain: newPersonaDomain,
          tagline: newPersonaTagline || undefined,
          autoGenerate: false,
        });

        if (response.data?.persona) {
          setPersonas(prev => [...prev, response.data.persona]);
          setSelectedPersona(response.data.persona);
        }
      }

      // Reset form
      setShowCreateForm(false);
      setNewPersonaName('');
      setNewPersonaTagline('');
      setGenerateTask('');
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to create persona';
      setError(message);
    } finally {
      setIsLoading(false);
      setIsGenerating(false);
    }
  };

  const handleActivatePersona = async (persona: PersonaProfile) => {
    setIsLoading(true);
    setError(null);

    try {
      await api.post(`/agentic/agents/${agentId}/personas/${persona.id}/activate`);
      setActivePersonaId(persona.id);
      onPersonaActivated?.(persona);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to activate persona';
      setError(message);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDeactivatePersona = async () => {
    setIsLoading(true);
    setError(null);

    try {
      await api.post(`/agentic/agents/${agentId}/personas/deactivate`);
      setActivePersonaId(null);
      onPersonaDeactivated?.();
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to deactivate persona';
      setError(message);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDeletePersona = async (personaId: string) => {
    if (!confirm('Are you sure you want to delete this persona? This cannot be undone.')) {
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      await api.delete(`/agentic/personas/${personaId}`);
      setPersonas(prev => prev.filter(p => p.id !== personaId));
      if (selectedPersona?.id === personaId) {
        setSelectedPersona(null);
      }
      if (activePersonaId === personaId) {
        setActivePersonaId(null);
        onPersonaDeactivated?.();
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to delete persona';
      setError(message);
    } finally {
      setIsLoading(false);
    }
  };

  const toggleSection = (section: string) => {
    setExpandedSection(prev => prev === section ? null : section);
  };

  // ============================================================================
  // Render
  // ============================================================================

  return (
    <div className={cn('space-y-6', className)}>
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-full bg-indigo-500/20">
            <Brain className="w-6 h-6 text-indigo-400" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-white">Persona Manager</h3>
            <p className="text-sm text-gray-400">
              Configure AI personalities for {agentName || 'this agent'}
            </p>
          </div>
        </div>
        <Button
          variant="primary"
          size="sm"
          icon={<UserPlus className="w-4 h-4" />}
          onClick={() => setShowCreateForm(true)}
        >
          New Persona
        </Button>
      </div>

      {error && (
        <div className="flex items-center gap-2 p-3 bg-red-500/10 border border-red-500/20 rounded-lg">
          <AlertCircle className="w-5 h-5 text-red-400" />
          <p className="text-sm text-red-400">{error}</p>
          <button
            onClick={() => setError(null)}
            className="ml-auto text-red-400 hover:text-red-300"
          >
            &times;
          </button>
        </div>
      )}

      {/* Create Persona Form */}
      {showCreateForm && (
        <div className="p-4 bg-slate-800/50 border border-slate-700 rounded-lg space-y-4">
          <div className="flex items-center justify-between">
            <h4 className="text-sm font-medium text-white">Create New Persona</h4>
            <button
              onClick={() => setShowCreateForm(false)}
              className="text-gray-400 hover:text-white"
            >
              &times;
            </button>
          </div>

          {/* Creation Mode Tabs */}
          <div className="flex gap-2">
            <button
              onClick={() => setCreateMode('generate')}
              className={cn(
                'flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-all',
                createMode === 'generate'
                  ? 'bg-indigo-500/20 border border-indigo-500/50 text-indigo-300'
                  : 'bg-slate-700/50 border border-slate-600 text-gray-400 hover:text-white'
              )}
            >
              <Wand2 className="w-4 h-4 inline mr-2" />
              Auto-Generate
            </button>
            <button
              onClick={() => setCreateMode('manual')}
              className={cn(
                'flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-all',
                createMode === 'manual'
                  ? 'bg-indigo-500/20 border border-indigo-500/50 text-indigo-300'
                  : 'bg-slate-700/50 border border-slate-600 text-gray-400 hover:text-white'
              )}
            >
              <Edit3 className="w-4 h-4 inline mr-2" />
              Manual
            </button>
          </div>

          {createMode === 'generate' ? (
            <>
              {/* Domain Selection */}
              <div className="space-y-2">
                <label className="text-sm text-gray-400">Domain (optional)</label>
                <select
                  value={newPersonaDomain}
                  onChange={(e) => setNewPersonaDomain(e.target.value as PersonaDomain)}
                  className="w-full p-2 bg-slate-800 border border-slate-600 rounded text-white text-sm"
                >
                  {ALL_DOMAINS.map(domain => (
                    <option key={domain} value={domain}>
                      {DOMAIN_LABELS[domain].label}
                    </option>
                  ))}
                </select>
              </div>

              {/* Task Description */}
              <div className="space-y-2">
                <label className="text-sm text-gray-400">
                  Describe the task this persona should handle
                </label>
                <textarea
                  value={generateTask}
                  onChange={(e) => setGenerateTask(e.target.value)}
                  placeholder="e.g., Help onboard new employees, create training materials, and answer HR policy questions..."
                  rows={3}
                  className="w-full p-3 bg-slate-800 border border-slate-600 rounded text-white text-sm placeholder:text-gray-500 resize-none"
                />
              </div>

              {isGenerating && (
                <div className="flex items-center gap-2 text-indigo-400">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span className="text-sm">Generating persona with AI...</span>
                </div>
              )}
            </>
          ) : (
            <>
              <Input
                label="Persona Name"
                value={newPersonaName}
                onChange={(e) => setNewPersonaName(e.target.value)}
                placeholder="e.g., Senior HR Specialist"
              />

              <div className="space-y-2">
                <label className="text-sm text-gray-400">Domain</label>
                <select
                  value={newPersonaDomain}
                  onChange={(e) => setNewPersonaDomain(e.target.value as PersonaDomain)}
                  className="w-full p-2 bg-slate-800 border border-slate-600 rounded text-white text-sm"
                >
                  {ALL_DOMAINS.map(domain => (
                    <option key={domain} value={domain}>
                      {DOMAIN_LABELS[domain].label}
                    </option>
                  ))}
                </select>
              </div>

              <Input
                label="Tagline (optional)"
                value={newPersonaTagline}
                onChange={(e) => setNewPersonaTagline(e.target.value)}
                placeholder="e.g., Building great teams through strategic talent management"
              />
            </>
          )}

          <div className="flex justify-end gap-2">
            <Button
              variant="ghost"
              onClick={() => setShowCreateForm(false)}
            >
              Cancel
            </Button>
            <Button
              variant="primary"
              onClick={handleCreatePersona}
              loading={isLoading}
              icon={createMode === 'generate' ? <Wand2 className="w-4 h-4" /> : <UserPlus className="w-4 h-4" />}
            >
              {createMode === 'generate' ? 'Generate Persona' : 'Create Persona'}
            </Button>
          </div>
        </div>
      )}

      {/* Personas List Section */}
      <div className="border border-slate-700 rounded-lg overflow-hidden">
        <button
          onClick={() => toggleSection('list')}
          className="w-full flex items-center justify-between p-4 bg-slate-800/50 hover:bg-slate-800/70 transition-colors"
        >
          <div className="flex items-center gap-2">
            <Users className="w-5 h-5 text-indigo-400" />
            <span className="font-medium text-white">
              Personas ({personas.length})
            </span>
            {activePersonaId && (
              <span className="text-xs px-2 py-0.5 bg-emerald-500/20 text-emerald-400 rounded-full">
                1 Active
              </span>
            )}
          </div>
          {expandedSection === 'list' ? (
            <ChevronDown className="w-5 h-5 text-gray-400" />
          ) : (
            <ChevronRight className="w-5 h-5 text-gray-400" />
          )}
        </button>

        {expandedSection === 'list' && (
          <div className="p-4 space-y-3">
            {isLoadingPersonas ? (
              <div className="flex items-center justify-center py-8 text-gray-400">
                <Loader2 className="w-6 h-6 animate-spin mr-2" />
                Loading personas...
              </div>
            ) : personas.length === 0 ? (
              <div className="text-center py-8">
                <Brain className="w-12 h-12 mx-auto text-gray-600 mb-3" />
                <p className="text-gray-400 mb-2">No personas yet</p>
                <p className="text-sm text-gray-500 mb-4">
                  Create a persona to give your agent a specialized identity
                </p>
                <Button
                  variant="outline"
                  size="sm"
                  icon={<Wand2 className="w-4 h-4" />}
                  onClick={() => {
                    setCreateMode('generate');
                    setShowCreateForm(true);
                  }}
                >
                  Auto-Generate Persona
                </Button>
              </div>
            ) : (
              personas.map((persona) => {
                const domainConfig = DOMAIN_LABELS[persona.domain];
                const isActive = persona.id === activePersonaId;
                const isSelected = persona.id === selectedPersona?.id;

                return (
                  <div
                    key={persona.id}
                    className={cn(
                      'p-4 rounded-lg border transition-all cursor-pointer',
                      isActive
                        ? 'bg-emerald-500/10 border-emerald-500/30'
                        : isSelected
                          ? 'bg-indigo-500/10 border-indigo-500/30'
                          : 'bg-slate-800/30 border-slate-700 hover:border-slate-600'
                    )}
                    onClick={() => setSelectedPersona(persona)}
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex items-start gap-3">
                        <div className={cn('p-2 rounded-lg bg-slate-800', domainConfig.color)}>
                          {domainConfig.icon}
                        </div>
                        <div>
                          <div className="flex items-center gap-2">
                            <span className="font-medium text-white">{persona.name}</span>
                            {isActive && (
                              <span className="text-xs px-2 py-0.5 bg-emerald-500/20 text-emerald-400 rounded-full">
                                Active
                              </span>
                            )}
                            {persona.isAutoGenerated && (
                              <span title="Auto-generated">
                                <Wand2 className="w-3 h-3 text-indigo-400" />
                              </span>
                            )}
                          </div>
                          <p className="text-sm text-gray-400">{persona.tagline}</p>
                          <div className="flex items-center gap-3 mt-2 text-xs text-gray-500">
                            <span className={domainConfig.color}>{domainConfig.label}</span>
                            <span>v{persona.version}</span>
                            <span>{persona.usageCount} uses</span>
                            <span>{Math.round(persona.successRate * 100)}% success</span>
                          </div>
                        </div>
                      </div>

                      <div className="flex items-center gap-2">
                        {isActive ? (
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={(e) => {
                              e.stopPropagation();
                              handleDeactivatePersona();
                            }}
                            loading={isLoading}
                          >
                            Deactivate
                          </Button>
                        ) : (
                          <Button
                            variant="outline"
                            size="sm"
                            icon={<CheckCircle className="w-4 h-4" />}
                            onClick={(e) => {
                              e.stopPropagation();
                              handleActivatePersona(persona);
                            }}
                            loading={isLoading}
                          >
                            Activate
                          </Button>
                        )}
                        <Button
                          variant="ghost"
                          size="sm"
                          icon={<Trash2 className="w-4 h-4 text-red-400" />}
                          onClick={(e) => {
                            e.stopPropagation();
                            handleDeletePersona(persona.id);
                          }}
                        />
                      </div>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        )}
      </div>

      {/* Selected Persona Details */}
      {selectedPersona && (
        <>
          {/* Skills Section */}
          <div className="border border-slate-700 rounded-lg overflow-hidden">
            <button
              onClick={() => toggleSection('skills')}
              className="w-full flex items-center justify-between p-4 bg-slate-800/50 hover:bg-slate-800/70 transition-colors"
            >
              <div className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-yellow-400" />
                <span className="font-medium text-white">
                  Skills & Expertise
                </span>
              </div>
              {expandedSection === 'skills' ? (
                <ChevronDown className="w-5 h-5 text-gray-400" />
              ) : (
                <ChevronRight className="w-5 h-5 text-gray-400" />
              )}
            </button>

            {expandedSection === 'skills' && (
              <div className="p-4 space-y-4">
                {/* Expertise */}
                <div>
                  <label className="text-xs text-gray-500 uppercase tracking-wide">
                    Areas of Expertise
                  </label>
                  <div className="flex flex-wrap gap-2 mt-2">
                    {selectedPersona.expertise.map((exp, i) => (
                      <span
                        key={i}
                        className="px-2 py-1 bg-slate-700/50 border border-slate-600 rounded text-sm text-gray-300"
                      >
                        {exp}
                      </span>
                    ))}
                  </div>
                </div>

                {/* Skills */}
                <div>
                  <label className="text-xs text-gray-500 uppercase tracking-wide">
                    Skills
                  </label>
                  <div className="space-y-2 mt-2">
                    {selectedPersona.skills.map((skill, i) => (
                      <div key={i} className="p-3 bg-slate-800/30 rounded-lg">
                        <div className="flex items-center justify-between mb-1">
                          <span className="text-sm font-medium text-white">{skill.name}</span>
                          <span className="text-xs text-gray-400">{skill.proficiency}%</span>
                        </div>
                        <p className="text-xs text-gray-500">{skill.description}</p>
                        <div className="mt-2 h-1 bg-slate-700 rounded-full overflow-hidden">
                          <div
                            className="h-full bg-indigo-500 rounded-full"
                            style={{ width: `${skill.proficiency}%` }}
                          />
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Analytics Section */}
          <div className="border border-slate-700 rounded-lg overflow-hidden">
            <button
              onClick={() => toggleSection('analytics')}
              className="w-full flex items-center justify-between p-4 bg-slate-800/50 hover:bg-slate-800/70 transition-colors"
            >
              <div className="flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-green-400" />
                <span className="font-medium text-white">Analytics</span>
              </div>
              {expandedSection === 'analytics' ? (
                <ChevronDown className="w-5 h-5 text-gray-400" />
              ) : (
                <ChevronRight className="w-5 h-5 text-gray-400" />
              )}
            </button>

            {expandedSection === 'analytics' && (
              <div className="p-4">
                {analytics ? (
                  <div className="space-y-6">
                    {/* Summary Stats Row */}
                    <div className="grid grid-cols-4 gap-3">
                      <div className="p-3 bg-slate-800/30 rounded-lg text-center">
                        <p className="text-xs text-gray-500 mb-1">Total Tasks</p>
                        <p className="text-xl font-bold text-white">{analytics.totalTasks}</p>
                      </div>
                      <div className="p-3 bg-slate-800/30 rounded-lg text-center">
                        <p className="text-xs text-gray-500 mb-1">Successful</p>
                        <p className="text-xl font-bold text-emerald-400">{analytics.successfulTasks}</p>
                      </div>
                      <div className="p-3 bg-slate-800/30 rounded-lg text-center">
                        <p className="text-xs text-gray-500 mb-1">Failed</p>
                        <p className="text-xl font-bold text-red-400">{analytics.failedTasks}</p>
                      </div>
                      <div className="p-3 bg-slate-800/30 rounded-lg text-center">
                        <p className="text-xs text-gray-500 mb-1">Learnings</p>
                        <p className="text-xl font-bold text-indigo-400">{analytics.learningCount}</p>
                      </div>
                    </div>

                    {/* Charts Row */}
                    <div className="grid grid-cols-3 gap-4">
                      {/* Success Rate Donut */}
                      <div className="p-4 bg-slate-800/30 rounded-lg">
                        <div className="flex items-center gap-2 mb-3">
                          <PieChart className="w-4 h-4 text-emerald-400" />
                          <p className="text-xs text-gray-400 uppercase tracking-wide">Success Rate</p>
                        </div>
                        <div className="flex justify-center relative">
                          <DonutChart
                            value={analytics.successfulTasks}
                            total={analytics.totalTasks}
                            label="Success"
                            color="#10B981"
                            size={100}
                          />
                        </div>
                      </div>

                      {/* Quality Gauge */}
                      <div className="p-4 bg-slate-800/30 rounded-lg">
                        <div className="flex items-center gap-2 mb-3">
                          <Activity className="w-4 h-4 text-amber-400" />
                          <p className="text-xs text-gray-400 uppercase tracking-wide">Quality Rating</p>
                        </div>
                        <div className="flex justify-center">
                          <QualityGauge
                            value={analytics.averageQualityRating}
                            maxValue={5}
                            size={120}
                          />
                        </div>
                      </div>

                      {/* Task Distribution */}
                      <div className="p-4 bg-slate-800/30 rounded-lg">
                        <div className="flex items-center gap-2 mb-3">
                          <BarChart3 className="w-4 h-4 text-indigo-400" />
                          <p className="text-xs text-gray-400 uppercase tracking-wide">Task Types</p>
                        </div>
                        <HorizontalBarChart
                          data={analytics.mostCommonTaskTypes}
                          maxItems={4}
                        />
                      </div>
                    </div>

                    {/* Skill Radar (if selected persona has skills) */}
                    {selectedPersona && selectedPersona.skills.length >= 3 && (
                      <div className="p-4 bg-slate-800/30 rounded-lg">
                        <div className="flex items-center gap-2 mb-4">
                          <Sparkles className="w-4 h-4 text-yellow-400" />
                          <p className="text-xs text-gray-400 uppercase tracking-wide">Skill Profile</p>
                        </div>
                        <div className="flex justify-center">
                          <SkillRadar skills={selectedPersona.skills} size={220} />
                        </div>
                      </div>
                    )}

                    {/* Last Active */}
                    {analytics.lastActiveAt && (
                      <div className="text-center text-xs text-gray-500">
                        Last active: {formatDateTime(analytics.lastActiveAt)}
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="text-center py-8">
                    <BarChart3 className="w-12 h-12 mx-auto text-gray-600 mb-3" />
                    <p className="text-gray-400 mb-2">No analytics available yet</p>
                    <p className="text-sm text-gray-500">
                      Execute tasks with this persona to start collecting analytics
                    </p>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Learnings Section */}
          <div className="border border-slate-700 rounded-lg overflow-hidden">
            <button
              onClick={() => toggleSection('learnings')}
              className="w-full flex items-center justify-between p-4 bg-slate-800/50 hover:bg-slate-800/70 transition-colors"
            >
              <div className="flex items-center gap-2">
                <Lightbulb className="w-5 h-5 text-amber-400" />
                <span className="font-medium text-white">
                  Learned Patterns ({learnings.length})
                </span>
              </div>
              {expandedSection === 'learnings' ? (
                <ChevronDown className="w-5 h-5 text-gray-400" />
              ) : (
                <ChevronRight className="w-5 h-5 text-gray-400" />
              )}
            </button>

            {expandedSection === 'learnings' && (
              <div className="p-4">
                {learnings.length > 0 ? (
                  <div className="space-y-2">
                    {learnings.slice(0, 5).map((learning) => (
                      <div
                        key={learning.id}
                        className="p-3 bg-slate-800/30 rounded-lg"
                      >
                        <div className="flex items-center justify-between mb-1">
                          <span className="text-xs px-2 py-0.5 bg-slate-700 rounded text-gray-400">
                            {learning.taskType}
                          </span>
                          <span className="text-xs text-gray-500">
                            {Math.round(learning.confidence * 100)}% confidence
                          </span>
                        </div>
                        <p className="text-sm text-gray-300 mt-2">{learning.pattern}</p>
                        <p className="text-xs text-gray-500 mt-1">
                          Applied {learning.applicationCount} times
                        </p>
                      </div>
                    ))}
                    {learnings.length > 5 && (
                      <p className="text-center text-sm text-gray-500">
                        +{learnings.length - 5} more learnings
                      </p>
                    )}
                  </div>
                ) : (
                  <p className="text-center text-gray-500 py-4">
                    No learned patterns yet. Execute tasks to build up learnings.
                  </p>
                )}
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
};

PersonaManagerPanel.displayName = 'PersonaManagerPanel';

export default PersonaManagerPanel;
